services:
  db:
    image: postgres:latest
    container_name: user_module
    restart: always
    environment:
      POSTGRES_USER: Ferremat
      POSTGRES_PASSWORD: PwD95ErRb7@l0L
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
